// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataAccessLayer_DatabaseFirst.Entities;

public partial class CustomerOrdersView
{
    public int CustomerId { get; set; }

    public string CustomerName { get; set; }

    public int OrderId { get; set; }

    public int? Rating { get; set; }

    public string Review { get; set; }

    public DateTime Date { get; set; }
}