// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataAccessLayer_DatabaseFirst.Entities;

public partial class Product
{
    public int Id { get; set; }

    public string Name { get; set; }

    public decimal? Price { get; set; }

    public string Image { get; set; }

    public string Description { get; set; }

    public int? DepartmentId { get; set; }

    public virtual Department Department { get; set; }

    public virtual ICollection<OrderProduct> OrderProducts { get; set; } = new List<OrderProduct>();
}