// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataAccessLayer_DatabaseFirst.Entities;

public partial class ProductSalesView
{
    public int ProductId { get; set; }

    public string ProductName { get; set; }

    public int? TotalAmountSold { get; set; }

    public int? NumberOfOrders { get; set; }
}