// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TPT.DataAccessLayer.Context;

#nullable disable

namespace TPT.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250409191041_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TPT.DataAccessLayer.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Fname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("TPT.DataAccessLayer.Entities.Admin", b =>
                {
                    b.HasBaseType("TPT.DataAccessLayer.Entities.Employee");

                    b.Property<string>("Manager")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SSN")
                        .HasColumnType("int");

                    b.ToTable("Admins", (string)null);
                });

            modelBuilder.Entity("TPT.DataAccessLayer.Entities.Developer", b =>
                {
                    b.HasBaseType("TPT.DataAccessLayer.Entities.Employee");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Salary")
                        .HasColumnType("int");

                    b.ToTable("Developers", (string)null);
                });

            modelBuilder.Entity("TPT.DataAccessLayer.Entities.Admin", b =>
                {
                    b.HasOne("TPT.DataAccessLayer.Entities.Employee", null)
                        .WithOne()
                        .HasForeignKey("TPT.DataAccessLayer.Entities.Admin", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TPT.DataAccessLayer.Entities.Developer", b =>
                {
                    b.HasOne("TPT.DataAccessLayer.Entities.Employee", null)
                        .WithOne()
                        .HasForeignKey("TPT.DataAccessLayer.Entities.Developer", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
